name: Node.js Build 

'on': 

  workflow_dispatch: {} 

  push: {} 

jobs: 

  build: 

    runs-on: ubuntu-latest 

    steps: 

      - uses: actions/checkout@v1 

        with: 

          fetch-depth: '0' 

      - uses: actions/setup-node@v2 

        with: 

          node-version: lts/* 
      - name: Update config.json 

        run: |- 

          echo "`jq '.translateService="/api"' public/config.json`" > public/config.json 
      - name: Build And Deploy 

        id: builddeploy 

        uses: Azure/static-web-apps-deploy@v1 

        with: 

          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} 

          repo_token: ${{ secrets.GITHUB_TOKEN }} 

          action: 'upload' 

          app_location: '/' 

          api_location: '' 
